### ISSUE TITLE
Provide more accurate timestamps

### ISSUE THREAD

**Issue by ojura** [larics/smartek_camera#4]
borrow PID time correction from aravis_camera

**Comment by dmiklic** [comment]
Another time sync scheme that we could possibly look into:

https://github.com/ethz-asl/visensor_node/wiki/ROS-Topics-and-Services

**Comment by dmiklic** [comment]
the [mavros](https://github.com/mavlink/mavros) package also has a timestamp sync scheme:

https://github.com/mavlink/mavros/blob/master/mavros/src/lib/uas_timesync.cpp
https://github.com/mavlink/mavros/blob/cafb05e79697fc8f1cb889ffac9e5b9d68183460/mavros/src/plugins/sys_time.cpp

**Comment by ojura** [comment]
The timesync class, which has been introduced in 69ed65e21292a898feac3fcbe9d658728bff2add, closes #4
